# Use the base Python image.
FROM python:3.8-slim

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /code

# Install dependencies
COPY requirements-worker.txt /code/
RUN pip install --no-cache-dir -r requirements-worker.txt

# Copy
COPY . /code/

# Expose port (for debugging)
EXPOSE 5000

CMD ["python", "worker.py"]
